import React, { useEffect, useState } from "react";
import Lottie from "lottie-react";
import AIdata from "../../assets/AIdata.json";
import "./Banner.css";
import { ShieldCheck, FileText, Search, Zap, Lock } from "lucide-react"; // ← icons

function usePrefersReducedMotion() {
  const [prefers, setPrefers] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const handler = () => setPrefers(mq.matches);
    handler();
    mq.addEventListener?.("change", handler);
    return () => mq.removeEventListener?.("change", handler);
  }, []);
  return prefers;
}

const StatCard = ({ src, alt, value, label }) => (
  <div className="stat-card">
    <div className="stat-icon">
      <img src={src} alt={alt} className="w-10 h-10" />
    </div>
    <div>
      <p className="text-3xl font-semibold text-gray-900 leading-none">{value}</p>
      <p className="text-sm text-gray-600 mt-1">{label}</p>
    </div>
  </div>
);

// === Live Activity Ticker (one item at a time) ===
const ActivityTicker = ({ reduceMotion = false }) => {
  const events = [
    { icon: ShieldCheck, text: "AI risk check successfully passed by a finance company" },
    { icon: FileText,   text: "New SOC 2 policy generated by a SaaS provider" },
    { icon: Search,     text: "Risk assessment completed by a healthcare company" },
    { icon: Zap,        text: "GDPR audit finished by an e-commerce business" },
    { icon: Lock,       text: "ISO 27001 encryption check passed by a tech startup" },
    { icon: ShieldCheck, text: "Security framework alignment verified by a fintech company" },
    { icon: FileText,   text: "Compliance documentation updated by a government agency" },
    { icon: Search,     text: "Privacy impact assessment completed by a nonprofit" },
    { icon: Zap,        text: "Data retention policy reviewed by a logistics company" },
    { icon: Lock,       text: "Multi-factor authentication audit passed by a legal firm" },
    { icon: ShieldCheck, text: "Incident response plan validated by an insurance provider" },
    { icon: FileText,   text: "Internal audit report generated by an educational institution" },
    { icon: Search,     text: "Third-party vendor risk check completed by a retail chain" },
    { icon: Zap,        text: "Access control policy updated by an AI startup" },
    { icon: Lock,       text: "Encryption key rotation verified by a telecom company" }
  ];
  

  const [idx, setIdx] = useState(0);

  useEffect(() => {
    if (reduceMotion) return; // no auto-animate for reduced motion
    const t = setInterval(() => {
      setIdx((i) => (i + 1) % events.length);
    }, 3200);
    return () => clearInterval(t);
  }, [reduceMotion, events.length]);

  const ItemIcon = events[idx].icon;

  return (
    <div className="ticker-wrapper" aria-live="polite" aria-atomic="true">
      <div key={idx} className={`ticker-chip ${reduceMotion ? "" : "animate-ticker-enter"}`}>
        <span className="ticker-icon-wrap">
          <ItemIcon className="w-4 h-4" />
        </span>
        <span className="ticker-text">{events[idx].text}</span>
      </div>
    </div>
  );
};

const Banner = () => {
  const reduceMotion = usePrefersReducedMotion();

  return (
    <section className="hero-section px-6 md:px-12">
      {/* subtle background texture */}
      <div className="hero-bg pointer-events-none" aria-hidden="true" />

      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 items-center gap-12">
        {/* LEFT */}
        <div className="space-y-7">
          <div>
            <p className="inline-flex items-center gap-2 text-xs font-medium text-emerald-700 bg-emerald-50 ring-1 ring-emerald-100 px-2.5 py-1 rounded-full">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
              Built for security-first teams
            </p>
            <h1 className="mt-4 leading-[1.05] font-semibold tracking-tight text-balance text-4xl md:text-5xl">
              <span className="hero-headline">
                AI-Powered Compliance.
                <br className="hidden md:block" />
                Built for Modern Startups.
              </span>
            </h1>
          </div>

          <p className="text-base md:text-lg text-gray-700 max-w-xl leading-relaxed">
            Automate audits, policy creation, and risk assessments. Stay aligned with SOC&nbsp;2, GDPR,
            and the EU AI Act—without hiring a legal team.
          </p>

          {/* Live Activity Ticker (replaces quick links / avoids duplicate demo CTA) */}
          <ActivityTicker reduceMotion={reduceMotion} />

          {/* Stats */}
          <div className="grid grid-cols-2 sm:flex sm:flex-wrap gap-6 pt-2">
            <StatCard src="/SVG/backup_table.svg" alt="Frameworks" value="20+" label="Frameworks supported" />
            <StatCard src="/SVG/atr.svg" alt="Risk Checks" value="1,000+" label="AI risk checks" />
          </div>

          {/* Trust strip */}
          <div className="flex flex-wrap items-center gap-3 pt-1">
            {["SOC 2–ready", "ISO 27001-aligned", "Enterprise SSO"].map((tag) => (
              <span key={tag} className="badge">{tag}</span>
            ))}
          </div>
        </div>

        {/* RIGHT */}
        <div className="relative flex justify-center md:justify-end">
          {/* soft glow */}
          <div className="hero-glow" aria-hidden="true" />

          {/* floating chips */}
          <div className={`floating-chip absolute -top-6 -left-6 z-20 ${reduceMotion ? "no-float" : "animate-float-slow"}`}>
            <img src="/SVG/link.svg" alt="Security" className="w-5 h-5" />
          </div>
          <div className={`floating-chip absolute -bottom-6 -right-6 z-20 ${reduceMotion ? "no-float" : "animate-float-slower"}`}>
            <img src="/SVG/gear.svg" alt="Automation" className="w-5 h-5" />
          </div>

          {/* text chips */}
          <div className={`floating-chip absolute top-1/3 -left-12 z-20 ${reduceMotion ? "no-float" : "animate-float-slow"}`}>
            SOC 2
          </div>
          <div className={`floating-chip absolute bottom-1/3 -right-12 z-20 ${reduceMotion ? "no-float" : "animate-float-slower"}`}>
            GDPR
          </div>

          {/* Lottie in device frame */}
          <div className="device-frame z-10">
            <div className="device-chrome">
              <span className="dot red" />
              <span className="dot yellow" />
              <span className="dot green" />
            </div>
            <div className="device-canvas">
              <Lottie
                animationData={AIdata}
                loop={!reduceMotion}
                autoplay={!reduceMotion}
                className="w-full h-auto"
                rendererSettings={{ preserveAspectRatio: "xMidYMid slice" }}
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Banner;
