import React, { useEffect, useState } from "react";
import Lottie from "lottie-react";
import AIdata from "../../assets/AIdata.json";
import { ShieldCheck, FileText, Search, Zap, Lock } from "lucide-react"; // ← icons

function usePrefersReducedMotion() {
  const [prefers, setPrefers] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const handler = () => setPrefers(mq.matches);
    handler();
    mq.addEventListener?.("change", handler);
    return () => mq.removeEventListener?.("change", handler);
  }, []);
  return prefers;
}

const StatCard = ({ src, alt, value, label }) => (
  <div className="flex items-center gap-4">
    <img src={src} alt={alt} className="w-10 h-10" />
    <div>
      <p className="text-3xl font-semibold text-gray-900 leading-none">{value}</p>
      <p className="text-sm text-gray-600 mt-1">{label}</p>
    </div>
  </div>
);

// === Live Activity Ticker (one item at a time) ===
const ActivityTicker = ({ reduceMotion = false }) => {
  const events = [
    { icon: ShieldCheck, text: "AI risk check successfully passed by a finance company" },
    { icon: FileText,   text: "New SOC 2 policy generated by a SaaS provider" },
    { icon: Search,     text: "Risk assessment completed by a healthcare company" },
    { icon: Zap,        text: "GDPR audit finished by an e-commerce business" },
    { icon: Lock,       text: "ISO 27001 encryption check passed by a tech startup" },
  ];

  const [idx, setIdx] = useState(0);

  useEffect(() => {
    if (reduceMotion) return;
    const t = setInterval(() => setIdx((i) => (i + 1) % events.length), 3200);
    return () => clearInterval(t);
  }, [reduceMotion]);

  const ItemIcon = events[idx].icon;
  return (
    <div className="mt-4 bg-gray-50 rounded-full px-4 py-2 flex items-center gap-2 text-sm text-gray-700 shadow-sm">
      <ItemIcon className="w-4 h-4 text-emerald-600" />
      {events[idx].text}
    </div>
  );
};

const Banner = () => {
  const reduceMotion = usePrefersReducedMotion();

  return (
    <section className="relative py-20">
      {/* FULL-BLEED WHITE BACKGROUND (escapes the parent container) */}
      <div
        className="
          absolute top-0 bottom-0 left-1/2 right-1/2 -mx-[50vw] w-screen
          bg-white -z-10
        "
        aria-hidden="true"
      />

      {/* CONTENT (kept inside your site container width) */}
      <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 items-center gap-12">
        {/* LEFT */}
        <div className="space-y-7">
          <div>
            <p className="inline-flex items-center gap-2 text-xs font-medium text-emerald-700 bg-emerald-50 ring-1 ring-emerald-100 px-2.5 py-1 rounded-full">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
              Built for security-first teams
            </p>
            <h1 className="mt-4 leading-[1.05] font-semibold tracking-tight text-balance text-4xl md:text-5xl text-gray-900">
              AI-Powered Compliance.
              <br className="hidden md:block" />
              Built for Modern Startups.
            </h1>
          </div>

          <p className="text-base md:text-lg text-gray-700 max-w-xl leading-relaxed">
            Automate audits, policy creation, and risk assessments. Stay aligned with SOC&nbsp;2, GDPR,
            and the EU AI Act—without hiring a legal team.
          </p>

          <ActivityTicker reduceMotion={reduceMotion} />

          {/* Stats */}
          <div className="grid grid-cols-2 gap-6 pt-2">
            <StatCard src="/SVG/backup_table.svg" alt="Frameworks" value="20+" label="Frameworks supported" />
            <StatCard src="/SVG/atr.svg" alt="Risk Checks" value="1,000+" label="AI risk checks" />
          </div>

          {/* Trust strip */}
          <div className="flex flex-wrap items-center gap-3 pt-1">
            {["SOC 2–ready", "ISO 27001-aligned", "Enterprise SSO"].map((tag) => (
              <span key={tag} className="px-3 py-1 text-xs font-medium text-gray-700 bg-gray-100 rounded-full">
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* RIGHT */}
        <div className="relative flex justify-center md:justify-end">
          {/* Device Frame */}
          <div className="w-full max-w-md bg-white border border-gray-200 rounded-xl shadow-lg overflow-hidden">
            <div className="bg-gray-100 px-4 py-2 flex gap-2">
              <span className="w-3 h-3 rounded-full bg-red-400"></span>
              <span className="w-3 h-3 rounded-full bg-yellow-400"></span>
              <span className="w-3 h-3 rounded-full bg-green-400"></span>
            </div>
            <div className="p-2">
              <Lottie
                animationData={AIdata}
                loop={!reduceMotion}
                autoplay={!reduceMotion}
                className="w-full h-auto"
                rendererSettings={{ preserveAspectRatio: "xMidYMid slice" }}
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Banner;

