import React, { useEffect, useState } from "react";
import { ShieldCheck, FileText, Search, Zap, Lock } from "lucide-react"; // icons

function usePrefersReducedMotion() {
  const [prefers, setPrefers] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const handler = () => setPrefers(mq.matches);
    handler();
    mq.addEventListener?.("change", handler);
    return () => mq.removeEventListener?.("change", handler);
  }, []);
  return prefers;
}

// === Live Activity Ticker (layout-stable) ===
const ActivityTicker = ({ reduceMotion = false }) => {
  const events = [
    { icon: ShieldCheck, text: "AI risk check successfully passed by a finance company" },
    { icon: FileText,   text: "New SOC 2 policy generated by a SaaS provider" },
    { icon: Search,     text: "Risk assessment completed by a healthcare company" },
    { icon: Zap,        text: "GDPR audit finished by an e-commerce business" },
    { icon: Lock,       text: "ISO 27001 encryption check passed by a tech startup" },
  ];

  const [idx, setIdx] = useState(0);
  const longestText = React.useMemo(
    () => events.reduce((m, e) => (e.text.length > m.length ? e.text : m), ""),
    []
  );

  useEffect(() => {
    if (reduceMotion) return;
    const t = setInterval(() => setIdx((i) => (i + 1) % events.length), 3200);
    return () => clearInterval(t);
  }, [reduceMotion, events.length]);

  const ItemIcon = events[idx].icon;

  return (
    <div
      className="relative mt-4 bg-gray-50 rounded-full px-4 py-2 text-sm text-gray-700 shadow-sm overflow-hidden"
      style={{ overflowAnchor: "none" }} // prevent scroll anchoring jumps
    >
      {/* Width + height reservation (invisible, no reflow on swap) */}
      <span className="invisible block whitespace-nowrap">
        <span className="inline-flex items-center gap-2">
          <ShieldCheck className="w-4 h-4" />
          {longestText}
        </span>
      </span>

      {/* Live content layered on top (no layout change) */}
      <div className="absolute inset-0 flex items-center px-4">
        <div
          key={idx}
          className={[
            "inline-flex items-center gap-2 whitespace-nowrap",
            reduceMotion ? "" : "transition-opacity duration-300",
          ].join(" ")}
          style={{ willChange: "opacity, transform" }}
        >
          <ItemIcon className="w-4 h-4 text-emerald-600" />
          {events[idx].text}
        </div>
      </div>
    </div>
  );
};


// === Bottom Facts Marquee ===
const FactsStrip = ({ reduceMotion = false }) => {
  const facts = [
    { icon: ShieldCheck, text: "Cut SOC 2 prep from 6 weeks to 5 days" },
    { icon: FileText,   text: "Generate policies mapped to SOC 2, ISO 27001, HIPAA" },
    { icon: Search,     text: "1,000+ automated AI risk checks" },
    { icon: Zap,        text: "Real-time control gap detection" },
    { icon: Lock,       text: "Built with least-privilege and SSO by default" },
    { icon: ShieldCheck,text: "Continuous evidence collection (no manual uploads)" },
    { icon: FileText,   text: "Export auditor-ready reports in 1 click" },
  ];

  if (reduceMotion) {
    // Accessible, no-motion fallback
    return (
      <div className="mt-10 border-t border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <ul className="flex flex-wrap gap-4 text-sm text-gray-700">
            {facts.map((f, i) => {
              const I = f.icon;
              return (
                <li key={i} className="inline-flex items-center gap-2">
                  <I className="w-4 h-4 text-emerald-600" />
                  {f.text}
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    );
  }

  // Animated marquee with edge fade & hover pause
  return (
    <>
      <style>
        {`
        @keyframes marqueeX { 0% { transform: translateX(0); } 100% { transform: translateX(-50%); } }
        .marquee-mask {
          -webkit-mask-image: linear-gradient(90deg, transparent, black 8%, black 92%, transparent);
                  mask-image: linear-gradient(90deg, transparent, black 8%, black 92%, transparent);
        }
        .marquee-track {
          animation: marqueeX 22s linear infinite;
        }
        .marquee-paused:hover .marquee-track { animation-play-state: paused; }
      `}
      </style>
      <div className="mt-10 border-t border-gray-200 bg-white/70 backdrop-blur">
        <div className="marquee-paused marquee-mask">
          <div className="max-w-none w-[200%]">
            <div className="marquee-track flex items-center gap-8 py-4 px-6 text-sm text-gray-800">
              {[...facts, ...facts].map((f, i) => {
                const I = f.icon;
                return (
                  <span key={i} className="inline-flex items-center gap-2 whitespace-nowrap">
                    <I className="w-4 h-4 text-emerald-600" />
                    {f.text}
                  </span>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

const Banner = () => {
  const reduceMotion = usePrefersReducedMotion();

  return (
    <section className="relative pt-20 pb-0">
      {/* Full-bleed background */}
      <div
        className="absolute top-0 bottom-0 left-1/2 right-1/2 -mx-[50vw] w-screen bg-white -z-10"
        aria-hidden="true"
      />

      <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 items-center gap-12">
        {/* LEFT */}
        <div className="space-y-7">
          <div>
            <p className="inline-flex items-center gap-2 text-xs font-medium text-emerald-700 bg-emerald-50 ring-1 ring-emerald-100 px-2.5 py-1 rounded-full">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
              Built for security-first teams
            </p>
            <h1 className="mt-4 leading-[1.05] font-semibold tracking-tight text-balance text-4xl md:text-5xl text-gray-900">
              Pass Every Audit. <br className="hidden md:block" />
              <span className="text-emerald-600">AI-Powered Compliance</span> for Startups.
            </h1>
          </div>

          <p className="text-base md:text-lg text-gray-700 max-w-xl leading-relaxed">
            Automate audits, policy creation, and risk assessments. Stay aligned with SOC&nbsp;2, GDPR,
            and the EU AI Act—without hiring a legal team.
          </p>

          <ActivityTicker reduceMotion={reduceMotion} />

          {/* Trust strip */}
          <div className="flex flex-wrap items-center gap-3 pt-1">
            {["SOC 2–ready", "ISO 27001-aligned", "Enterprise SSO"].map((tag) => (
              <span
                key={tag}
                className="inline-flex items-center gap-1 px-3 py-1 text-xs font-medium text-gray-700 bg-gradient-to-r from-gray-100 to-gray-50 rounded-full"
              >
                <ShieldCheck className="w-3 h-3 text-emerald-600" />
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* RIGHT — Frameworks Panel */}
        <div className="relative flex justify-center md:justify-end">
          {/* Glow accent */}
          <div className="absolute inset-0 flex justify-center">
            <div className="h-64 w-64 rounded-full bg-emerald-200/30 blur-3xl animate-pulse-slow"></div>
          </div>

          <div className="relative w-full max-w-lg rounded-2xl border border-gray-200 bg-white/80 backdrop-blur-sm shadow-xl p-6">
            <p className="mb-1 text-base font-semibold text-gray-900">
              Global Compliance Standards
            </p>
            <p className="mb-6 text-sm text-gray-600">
              Trusted by enterprises worldwide to meet and maintain security compliance.
            </p>

            {/* Logo grid */}
            <ul className="grid grid-cols-3 gap-6">
              {[
                { label: "SOC 2", file: "soc2.png", badge: "Most Requested" },
                { label: "ISO 27001", file: "iso27001.png" },
                { label: "GDPR", file: "gdpr.png" },
                { label: "HIPAA", file: "hipaa.png" },
                { label: "NIST CSF", file: "nistcsf.png" },
                { label: "PCI DSS", file: "pcidss.png" },
              ].map(({ label, file, badge }) => (
                <li
                  key={label}
                  className="group relative flex items-center justify-center rounded-xl border border-gray-100 bg-gray-50/80 p-5 shadow-sm transition-transform duration-200 hover:-translate-y-1 hover:shadow-lg hover:border-emerald-500"
                  title={label}
                >
                  {badge && (
                    <span className="absolute -top-2 right-2 rounded-full bg-emerald-500 px-2 py-0.5 text-[10px] font-medium text-white shadow">
                      {badge}
                    </span>
                  )}
                  <img
                    src={`/frameworks/${file}`}
                    alt={`${label} logo`}
                    className="h-16 w-auto object-contain grayscale opacity-80 group-hover:grayscale-0 group-hover:opacity-100 transition"
                    loading="lazy"
                    decoding="async"
                  />
                </li>
              ))}
            </ul>

            {/* Bottom CTA */}
            <div className="mt-8">
              <a
                href="/frameworks"
                className="inline-flex items-center justify-center w-full rounded-lg bg-gray-900 px-4 py-3 text-base font-semibold text-white hover:bg-gray-800 transition-colors"
              >
                View all frameworks
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom moving facts strip */}
      <FactsStrip reduceMotion={reduceMotion} />
    </section>
  );
};

export default Banner;
